apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: springbootapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootapp1
  template:
    metadata:
      labels:
        app: springbootapp1
    spec:
      containers:
      - name: spring-boot
        image: chetana249/spring-boot-docker10-ubuntu
        ports:
        - containerPort: 8080
        
        

        

